version: "3.9"
services:
  web:
    ports:
      - 3001:3001
    depends_on:
      - postgres
    links:
      - postgres
    working_dir: /app
    build:
      context: .
    volumes:
      - .:/app
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "postgres"
